### ISSUE TITLE
Bug: ref for answers points to users

### ISSUE THREAD

**Issue by psitronic** [chingu-voyage7/Bears-Team-17#9]
re: db refs. Not sure what you are getting at, my point was that the ref for answers points to users 😕

_Originally posted by @nikrb in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ0MzY3NTY1Mg==/timeline/issue_comment#issuecomment-443675652_

**Comment by nikrb** [comment]
answers field in question table.
comments field in answers table.
